# Reduce logging level to make sure the application works with SAM local
# https://github.com/aws/serverless-java-container/issues/134
logging.level.root=WARN
logging.level.org.example=INFO

aws.s3.bucket=${S3_BUCKET:raahhuul-spring-boot-test}
aws.s3.region=${S3_REGION:ap-south-1}
aws.sqs.queue-url=${SQS_QUEUE_URL:https://sqs.ap-south-1.amazonaws.com/085608568709/CourseEventQueue}